"use client";

import { LibrarySection } from "../types/reportModuleTypes";

export const initialLibrarySections: LibrarySection[] = [
  {
    id: "sec-core-1",
    name: "Key Metrics This Month",
    titleHtml: '<span style="color:#0f172a">Key Metrics </span><span style="color:#2563eb">This Month</span>',
    eyebrow: "PROJECT OVERVIEW",
    eyebrowHtml: '<span style="color:#64748b">PROJECT OVERVIEW</span>',
    description: "A snapshot of your site's safety, compliance and device performance.",
    type: "core",
    icon: "Activity",
    updatedAt: "2026-10-05 17:35",
    projectSite: "ABC Infrastructure Project",
    reportingPeriod: "01 Sept 2025 – 30 Sept 2025",
    metricCards: [
      {
        id: "mc-1",
        label: "Monthly Attendance Rate",
        value: "92.4%",
        dataSourceField: "attendance_rate",
        tintColor: "blue",
        trendDirection: "up",
        trendValue: "+2.1%",
        trendSubtitle: "vs. last month",
        trendColor: "green",
        icon: "Users",
      },
      {
        id: "mc-2",
        label: "Monthly Compliance Rate",
        value: "96.8%",
        dataSourceField: "compliance_rate",
        tintColor: "emerald",
        trendDirection: "up",
        trendValue: "+3.6%",
        trendSubtitle: "vs. last month",
        trendColor: "green",
        icon: "ShieldCheck",
      },
      {
        id: "mc-3",
        label: "Total Devices Sent to Site",
        value: "300",
        dataSourceField: "devices_deployed",
        tintColor: "purple",
        trendDirection: "no-change",
        trendValue: "No change",
        trendSubtitle: "vs. last month",
        trendColor: "neutral",
        icon: "Package",
      },
      {
        id: "mc-4",
        label: "Damaged Devices This Month",
        value: "5",
        dataSourceField: "damaged_devices",
        tintColor: "red",
        trendDirection: "up",
        trendValue: "+2",
        trendSubtitle: "vs. last month",
        trendColor: "red",
        higherIsBetter: false,
        icon: "AlertTriangle",
      },
      {
        id: "mc-5",
        label: "Risk-Free Working Hours",
        value: "18,450 hrs",
        dataSourceField: "risk_free_hours",
        tintColor: "green",
        trendDirection: "up",
        trendValue: "+12%",
        trendSubtitle: "vs. last month",
        trendColor: "green",
        unit: "hrs",
        higherIsBetter: true,
        icon: "Clock",
      },
      {
        id: "mc-6",
        label: "Monthly Supervisory Efficiency",
        value: "89.2%",
        dataSourceField: "supervisory_efficiency",
        tintColor: "amber",
        trendDirection: "up",
        trendValue: "+4.5%",
        trendSubtitle: "vs. last month",
        trendColor: "green",
        higherIsBetter: true,
        icon: "UserCheck",
      },
      {
        id: "mc-7",
        label: "Total Runtime of Devices",
        value: "26,340 hrs",
        dataSourceField: "total_runtime",
        tintColor: "cyan",
        trendDirection: "up",
        trendValue: "+8%",
        trendSubtitle: "vs. last month",
        trendColor: "green",
        unit: "hrs",
        higherIsBetter: true,
        icon: "Settings",
      },
      {
        id: "mc-8",
        label: "Overtime of Devices",
        value: "320 hrs",
        dataSourceField: "overtime_hours",
        tintColor: "purple",
        trendDirection: "down",
        trendValue: "-28%",
        trendSubtitle: "vs. last month (Lower is better)",
        trendColor: "green",
        unit: "hrs",
        higherIsBetter: false,
        icon: "History",
      },
    ],
    charts: [],
    keyInsights: [
      {
        id: "ki-takeaways-1",
        variant: "vertical-takeaways",
        title: "Key Takeaways",
        text: "A complete overview of workforce safety, device utilisation and operational performance.",
        items: [
          {
            id: "kib-1",
            num: 1,
            color: "blue",
            title: "Attendance Rate",
            text: "92.4% of the registered workforce was present on-site this month, showing a 2.1% improvement from last month.",
          },
          {
            id: "kib-2",
            num: 2,
            color: "green",
            title: "Compliance Rate",
            text: "PPE compliance stood at 96.8%, reflecting strong adherence and a 3.6% improvement.",
          },
          {
            id: "kib-3",
            num: 3,
            color: "purple",
            title: "Devices Sent",
            text: "A total of 300 devices were deployed at the site, with no change from last month.",
          },
          {
            id: "kib-4",
            num: 4,
            color: "red",
            title: "Damaged Devices",
            text: "5 devices were reported damaged this month, an increase of 2 compared to last month.",
          },
          {
            id: "kib-5",
            num: 5,
            color: "mint",
            title: "Risk-Free Working Hours",
            text: "18,450 hours were recorded without any high-risk incidents, marking a 12% increase.",
          },
          {
            id: "kib-6",
            num: 6,
            color: "amber",
            title: "Supervisory Efficiency",
            text: "Supervisors responded and resolved violations with 89.2% efficiency, up by 4.5%.",
          },
          {
            id: "kib-7",
            num: 7,
            color: "cyan",
            title: "Total Runtime",
            text: "Devices operated for a total of 26,340 hours, an 8% increase, ensuring consistent site coverage.",
          },
          {
            id: "kib-8",
            num: 8,
            color: "teal",
            title: "Overtime of Devices",
            text: "Devices logged 320 hours of overtime, a 28% reduction from last month, indicating improved deployment management.",
          },
        ],
      },
    ],
    stamps: [
      {
        id: "coord-cell-km-1",
        sourceId: "cell-km-1",
        name: "Monthly Attendance Rate",
        pageIndex: 0,
        x: 24,
        y: 200,
        width: 130,
        height: 118,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-1",
          label: "Monthly Attendance Rate",
          value: "92.4%",
          dataSourceField: "attendance_rate",
          tintColor: "blue",
          trendDirection: "up",
          trendValue: "+2.1%",
          trendSubtitle: "vs. last month",
          trendColor: "green",
          icon: "Users",
        },
      },
      {
        id: "coord-cell-km-2",
        sourceId: "cell-km-2",
        name: "Monthly Compliance Rate",
        pageIndex: 0,
        x: 163,
        y: 200,
        width: 130,
        height: 118,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-2",
          label: "Monthly Compliance Rate",
          value: "96.8%",
          dataSourceField: "compliance_rate",
          tintColor: "emerald",
          trendDirection: "up",
          trendValue: "+3.6%",
          trendSubtitle: "vs. last month",
          trendColor: "green",
          icon: "ShieldCheck",
        },
      },
      {
        id: "coord-cell-km-3",
        sourceId: "cell-km-3",
        name: "Total Devices Sent to Site",
        pageIndex: 0,
        x: 302,
        y: 200,
        width: 130,
        height: 118,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-3",
          label: "Total Devices Sent to Site",
          value: "300",
          dataSourceField: "devices_deployed",
          tintColor: "purple",
          trendDirection: "no-change",
          trendValue: "No change",
          trendSubtitle: "vs. last month",
          trendColor: "neutral",
          icon: "Package",
        },
      },
      {
        id: "coord-cell-km-4",
        sourceId: "cell-km-4",
        name: "Damaged Devices This Month",
        pageIndex: 0,
        x: 441,
        y: 200,
        width: 130,
        height: 118,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-4",
          label: "Damaged Devices This Month",
          value: "5",
          dataSourceField: "damaged_devices",
          tintColor: "red",
          trendDirection: "up",
          trendValue: "+2",
          trendSubtitle: "vs. last month",
          trendColor: "red",
          higherIsBetter: false,
          icon: "AlertTriangle",
        },
      },
      {
        id: "coord-cell-km-5",
        sourceId: "cell-km-5",
        name: "Risk-Free Working Hours",
        pageIndex: 0,
        x: 24,
        y: 328,
        width: 130,
        height: 118,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-5",
          label: "Risk-Free Working Hours",
          value: "18,450 hrs",
          dataSourceField: "risk_free_hours",
          tintColor: "green",
          trendDirection: "up",
          trendValue: "+12%",
          trendSubtitle: "vs. last month",
          trendColor: "green",
          unit: "hrs",
          higherIsBetter: true,
          icon: "Clock",
        },
      },
      {
        id: "coord-cell-km-6",
        sourceId: "cell-km-6",
        name: "Monthly Supervisory Efficiency",
        pageIndex: 0,
        x: 163,
        y: 328,
        width: 130,
        height: 118,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-6",
          label: "Monthly Supervisory Efficiency",
          value: "89.2%",
          dataSourceField: "supervisory_efficiency",
          tintColor: "amber",
          trendDirection: "up",
          trendValue: "+4.5%",
          trendSubtitle: "vs. last month",
          trendColor: "green",
          higherIsBetter: true,
          icon: "UserCheck",
        },
      },
      {
        id: "coord-cell-km-7",
        sourceId: "cell-km-7",
        name: "Total Runtime of Devices",
        pageIndex: 0,
        x: 302,
        y: 328,
        width: 130,
        height: 118,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-7",
          label: "Total Runtime of Devices",
          value: "26,340 hrs",
          dataSourceField: "total_runtime",
          tintColor: "cyan",
          trendDirection: "up",
          trendValue: "+8%",
          trendSubtitle: "vs. last month",
          trendColor: "green",
          unit: "hrs",
          higherIsBetter: true,
          icon: "Settings",
        },
      },
      {
        id: "coord-cell-km-8",
        sourceId: "cell-km-8",
        name: "Overtime of Devices",
        pageIndex: 0,
        x: 441,
        y: 328,
        width: 130,
        height: 118,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-8",
          label: "Overtime of Devices",
          value: "320 hrs",
          dataSourceField: "overtime_hours",
          tintColor: "purple",
          trendDirection: "down",
          trendValue: "-28%",
          trendSubtitle: "vs. last month (Lower is better)",
          trendColor: "green",
          unit: "hrs",
          higherIsBetter: false,
          icon: "History",
        },
      },
      {
        id: "coord-cell-km-takeaways",
        sourceId: "cell-km-takeaways",
        name: "Key Takeaways",
        pageIndex: 0,
        x: 24,
        y: 456,
        width: 547,
        height: 250,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "insight",
        insight: {
          id: "ki-takeaways-1",
          variant: "vertical-takeaways",
          title: "Key Takeaways",
          text: "A complete overview of workforce safety, device utilisation and operational performance.",
          items: [
            {
              id: "kib-1",
              num: 1,
              color: "blue",
              title: "Attendance Rate",
              text: "92.4% of the registered workforce was present on-site this month, showing a 2.1% improvement from last month.",
            },
            {
              id: "kib-2",
              num: 2,
              color: "green",
              title: "Compliance Rate",
              text: "PPE compliance stood at 96.8%, reflecting strong adherence and a 3.6% improvement.",
            },
            {
              id: "kib-3",
              num: 3,
              color: "purple",
              title: "Devices Sent",
              text: "A total of 300 devices were deployed at the site, with no change from last month.",
            },
            {
              id: "kib-4",
              num: 4,
              color: "red",
              title: "Damaged Devices",
              text: "5 devices were reported damaged this month, an increase of 2 compared to last month.",
            },
            {
              id: "kib-5",
              num: 5,
              color: "mint",
              title: "Risk-Free Working Hours",
              text: "18,450 hours were recorded without any high-risk incidents, marking a 12% increase.",
            },
            {
              id: "kib-6",
              num: 6,
              color: "amber",
              title: "Supervisory Efficiency",
              text: "Supervisors responded and resolved violations with 89.2% efficiency, up by 4.5%.",
            },
            {
              id: "kib-7",
              num: 7,
              color: "cyan",
              title: "Total Runtime",
              text: "Devices operated for a total of 26,340 hours, an 8% increase, ensuring consistent site coverage.",
            },
            {
              id: "kib-8",
              num: 8,
              color: "teal",
              title: "Overtime of Devices",
              text: "Devices logged 320 hours of overtime, a 28% reduction from last month, indicating improved deployment management.",
            },
          ],
        },
      },
    ],
  },
  {
    id: "sec-core-2",
    name: "Attendance Trends",
    titleHtml: '<span style="color:#0f172a">Attendance </span><span style="color:#2563eb">Trends</span>',
    eyebrow: "ATTENDANCE ANALYSIS",
    eyebrowHtml: '<span style="color:#0f172a">ATTENDANCE </span><span style="color:#2563eb">ANALYSIS</span>',
    description: "Tracking workforce presence, punctuality and discipline.",
    type: "core",
    icon: "TrendingUp",
    updatedAt: "2026-09-22 15:10",
    metricCards: [
      {
        id: "mc-att-1",
        label: "Registered Workers",
        value: "300",
        dataSourceField: "registered_workers",
        tintColor: "blue",
        trendDirection: "no-change",
        trendValue: "",
        icon: "Users",
        cardVariant: "horizontal",
      },
      {
        id: "mc-att-2",
        label: "Average Daily Present",
        value: "276",
        dataSourceField: "average_daily_present",
        tintColor: "emerald",
        trendDirection: "up",
        trendValue: "+4.2%",
        trendSubtitle: "vs. last month",
        trendColor: "green",
        icon: "UserCheck",
        cardVariant: "horizontal",
      },
      {
        id: "mc-att-3",
        label: "Attendance Rate",
        value: "92.4%",
        dataSourceField: "attendance_rate",
        tintColor: "blue",
        trendDirection: "up",
        trendValue: "+2.1%",
        trendSubtitle: "vs. last month",
        trendColor: "green",
        icon: "Users",
        cardVariant: "horizontal",
      },
      {
        id: "mc-att-outlier-1",
        label: "Most Absent Worker",
        trendValue: "Rajesh Kumar",
        secondaryLabel: "(Emp ID: W1876)",
        value: "12",
        unit: "days absent",
        dataSourceField: "most_absent_worker",
        tintColor: "red",
        trendDirection: "down",
        icon: "User",
        cardVariant: "outlier",
        customIconBg: "#fee2e2",
        customIconColor: "#dc2626",
        customValueColor: "#dc2626",
      },
      {
        id: "mc-att-outlier-2",
        label: "Vendor with Most Absentees",
        trendValue: "Shakti Construction Services",
        value: "28",
        unit: "absent workers",
        dataSourceField: "vendor_most_absentees",
        tintColor: "purple",
        trendDirection: "down",
        icon: "Users",
        cardVariant: "outlier",
        customIconBg: "#ede9fe",
        customIconColor: "#7c3aed",
        customValueColor: "#6366f1",
      },
    ],
    charts: [
      {
        id: "ch-att-1",
        title: "Workers Present Throughout the Month",
        subtitle: "Daily count of workers present on-site.",
        icon: "Users",
        chartType: "line",
        dataSourceField: "workers_present_daily",
        color: "#10b981",
        headerKpi: {
          average: "276 / 300",
          highest: "302 (24 Sep)",
          lowest: "248 (8 Sep)",
        },
        xAxis: {
          title: "Date (September 2025)",
          labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"],
        },
        yAxis: {
          title: "Number of Workers",
          min: 0,
          max: 350,
          step: 50,
          unit: "",
        },
        series: [
          {
            id: "s-workers-present",
            name: "Workers Present",
            color: "#10b981",
            data: [275, 282, 295, 298, 290, 285, 265, 248, 268, 288, 290, 295, 290, 285, 275, 266, 280, 288, 285, 292, 287, 249, 270, 302, 301, 308, 285, 282, 275, 288],
          },
        ],
        options: {
          showValues: false,
          showGridLines: true,
          smoothCurve: false,
        },
      },
      {
        id: "ch-att-2",
        title: "Late Coming vs. Early Exits",
        subtitle: "Daily count of workers who arrived late or left early.",
        icon: "Clock",
        chartType: "line",
        dataSourceField: "late_early_exits_daily",
        colors: ["#f59e0b", "#f43f5e"],
        xAxis: {
          title: "Date (September 2025)",
          labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"],
        },
        yAxis: {
          title: "Number of Workers",
          min: 0,
          max: 50,
          step: 10,
          unit: "",
        },
        series: [
          {
            id: "s-late-coming",
            name: "Late Coming Workers",
            color: "#f59e0b",
            data: [20, 19, 23, 20, 24, 25, 33, 41, 28, 23, 20, 18, 20, 23, 26, 27, 22, 24, 24, 22, 27, 36, 27, 21, 19, 19, 21, 21, 27, 21],
          },
          {
            id: "s-early-exits",
            name: "Early Exits Workers",
            color: "#f43f5e",
            data: [10, 9, 8, 7, 10, 10, 15, 21, 13, 9, 8, 6, 8, 9, 10, 14, 9, 7, 9, 7, 10, 20, 13, 9, 7, 7, 10, 8, 13, 10],
          },
        ],
        options: {
          showValues: false,
          showGridLines: true,
          showLegend: true,
          legendPosition: "header",
          smoothCurve: false,
        },
      },
    ],
    keyInsights: [
      {
        id: "ki-att-1",
        variant: "narrative-summary",
        title: "Key Insights",
        text: "<p>The site maintained a strong workforce presence throughout the month, with an average of <strong>276 workers present daily</strong>, resulting in an <strong>attendance rate of 92.4%</strong>, which is a <strong>2.1% improvement</strong> from last month.</p><p>A total of <strong>412 instances of late coming</strong> and <strong>196 instances of early exits</strong> were recorded this month, with noticeable spikes around <strong>8 September</strong> and <strong>22 September</strong>, indicating periods of reduced punctuality.</p><p>The most absent worker this month was <strong>Rajesh Kumar</strong> (Emp ID: W1876), with <strong>12 days</strong> of absence.</p><p>The vendor with the most absentees was <strong>Shakti Construction Services</strong>, with a total of <strong>28 absent workers</strong>.</p><p>Overall, attendance remained stable, but continued focus on punctuality and shift discipline is recommended, especially during identified spike periods.</p>",
      },
    ],
    stamps: [
      {
        id: "coord-att-mc-1",
        sourceId: "mc-att-1",
        name: "Registered Workers",
        pageIndex: 0,
        x: 24,
        y: 195,
        width: 175,
        height: 78,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-att-1",
          label: "Registered Workers",
          value: "300",
          dataSourceField: "registered_workers",
          tintColor: "blue",
          trendDirection: "no-change",
          trendValue: "",
          icon: "Users",
          cardVariant: "horizontal",
        },
      },
      {
        id: "coord-att-mc-2",
        sourceId: "mc-att-2",
        name: "Average Daily Present",
        pageIndex: 0,
        x: 210,
        y: 195,
        width: 175,
        height: 78,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-att-2",
          label: "Average Daily Present",
          value: "276",
          dataSourceField: "average_daily_present",
          tintColor: "emerald",
          trendDirection: "up",
          trendValue: "+4.2%",
          trendSubtitle: "vs. last month",
          trendColor: "green",
          icon: "UserCheck",
          cardVariant: "horizontal",
        },
      },
      {
        id: "coord-att-mc-3",
        sourceId: "mc-att-3",
        name: "Attendance Rate",
        pageIndex: 0,
        x: 396,
        y: 195,
        width: 175,
        height: 78,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-att-3",
          label: "Attendance Rate",
          value: "92.4%",
          dataSourceField: "attendance_rate",
          tintColor: "blue",
          trendDirection: "up",
          trendValue: "+2.1%",
          trendSubtitle: "vs. last month",
          trendColor: "green",
          icon: "Users",
          cardVariant: "horizontal",
        },
      },
      {
        id: "coord-att-ch-1",
        sourceId: "ch-att-1",
        name: "Workers Present Throughout the Month",
        pageIndex: 0,
        x: 24,
        y: 283,
        width: 547,
        height: 170,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "chart",
        chart: {
          id: "ch-att-1",
          title: "Workers Present Throughout the Month",
          subtitle: "Daily count of workers present on-site.",
          icon: "Users",
          chartType: "line",
          dataSourceField: "workers_present_daily",
          color: "#10b981",
          headerKpi: {
            average: "276 / 300",
            highest: "302 (24 Sep)",
            lowest: "248 (8 Sep)",
          },
          xAxis: {
            title: "Date (September 2025)",
            labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"],
          },
          yAxis: {
            title: "Number of Workers",
            min: 0,
            max: 350,
            step: 50,
            unit: "",
          },
          series: [
            {
              id: "s-workers-present",
              name: "Workers Present",
              color: "#10b981",
              data: [275, 282, 295, 298, 290, 285, 265, 248, 268, 288, 290, 295, 290, 285, 275, 266, 280, 288, 285, 292, 287, 249, 270, 302, 301, 308, 285, 282, 275, 288],
            },
          ],
          options: {
            showValues: false,
            showGridLines: true,
            smoothCurve: false,
          },
        },
      },
      {
        id: "coord-att-ch-2",
        sourceId: "ch-att-2",
        name: "Late Coming vs. Early Exits",
        pageIndex: 0,
        x: 24,
        y: 463,
        width: 547,
        height: 160,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "chart",
        chart: {
          id: "ch-att-2",
          title: "Late Coming vs. Early Exits",
          subtitle: "Daily count of workers who arrived late or left early.",
          icon: "Clock",
          chartType: "line",
          dataSourceField: "late_early_exits_daily",
          colors: ["#f59e0b", "#f43f5e"],
          xAxis: {
            title: "Date (September 2025)",
            labels: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30"],
          },
          yAxis: {
            title: "Number of Workers",
            min: 0,
            max: 50,
            step: 10,
            unit: "",
          },
          series: [
            {
              id: "s-late-coming",
              name: "Late Coming Workers",
              color: "#f59e0b",
              data: [20, 19, 23, 20, 24, 25, 33, 41, 28, 23, 20, 18, 20, 23, 26, 27, 22, 24, 24, 22, 27, 36, 27, 21, 19, 19, 21, 21, 27, 21],
            },
            {
              id: "s-early-exits",
              name: "Early Exits Workers",
              color: "#f43f5e",
              data: [10, 9, 8, 7, 10, 10, 15, 21, 13, 9, 8, 6, 8, 9, 10, 14, 9, 7, 9, 7, 10, 20, 13, 9, 7, 7, 10, 8, 13, 10],
            },
          ],
          options: {
            showValues: false,
            showGridLines: true,
            showLegend: true,
            legendPosition: "header",
            smoothCurve: false,
          },
        },
      },
      {
        id: "coord-att-ki-narrative",
        sourceId: "ki-att-1",
        name: "Key Insights",
        pageIndex: 0,
        x: 24,
        y: 633,
        width: 335,
        height: 145,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "insight",
        insight: {
          id: "ki-att-1",
          variant: "narrative-summary",
          title: "Key Insights",
          text: "<p>The site maintained a strong workforce presence throughout the month, with an average of <strong>276 workers present daily</strong>, resulting in an <strong>attendance rate of 92.4%</strong>, which is a <strong>2.1% improvement</strong> from last month.</p><p>A total of <strong>412 instances of late coming</strong> and <strong>196 instances of early exits</strong> were recorded this month, with noticeable spikes around <strong>8 September</strong> and <strong>22 September</strong>, indicating periods of reduced punctuality.</p><p>The most absent worker this month was <strong>Rajesh Kumar</strong> (Emp ID: W1876), with <strong>12 days</strong> of absence.</p><p>The vendor with the most absentees was <strong>Shakti Construction Services</strong>, with a total of <strong>28 absent workers</strong>.</p><p>Overall, attendance remained stable, but continued focus on punctuality and shift discipline is recommended, especially during identified spike periods.</p>",
        },
      },
      {
        id: "coord-att-outlier-1",
        sourceId: "mc-att-outlier-1",
        name: "Most Absent Worker",
        pageIndex: 0,
        x: 369,
        y: 633,
        width: 202,
        height: 68,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-att-outlier-1",
          label: "Most Absent Worker",
          trendValue: "Rajesh Kumar",
          secondaryLabel: "(Emp ID: W1876)",
          value: "12",
          unit: "days absent",
          dataSourceField: "most_absent_worker",
          tintColor: "red",
          trendDirection: "down",
          icon: "User",
          cardVariant: "outlier",
          customIconBg: "#fee2e2",
          customIconColor: "#dc2626",
          customValueColor: "#dc2626",
        },
      },
      {
        id: "coord-att-outlier-2",
        sourceId: "mc-att-outlier-2",
        name: "Vendor with Most Absentees",
        pageIndex: 0,
        x: 369,
        y: 710,
        width: 202,
        height: 68,
        rotation: 0,
        opacity: 100,
        layer: "front",
        elementType: "metric-card",
        metricCard: {
          id: "mc-att-outlier-2",
          label: "Vendor with Most Absentees",
          trendValue: "Shakti Construction Services",
          value: "28",
          unit: "absent workers",
          dataSourceField: "vendor_most_absentees",
          tintColor: "purple",
          trendDirection: "down",
          icon: "Users",
          cardVariant: "outlier",
          customIconBg: "#ede9fe",
          customIconColor: "#7c3aed",
          customValueColor: "#6366f1",
        },
      },
    ],
  },
  {
    id: "sec-core-3",
    name: "PPE Compliance Trends",
    eyebrow: "SAFETY COMPLIANCE",
    description: "Real-time BLE mesh telemetry tracking Smart Helmets, Vest IoT Hubs, and Anti-Slip Boot Grounding.",
    type: "core",
    icon: "Shield",
    updatedAt: "2026-09-21 16:45",
    metricCards: [
      {
        id: "mc-8",
        label: "Smart Helmet Telemetry",
        value: "99.4%",
        dataSourceField: "smart_helmet",
        tintColor: "blue",
        trendDirection: "up",
        trendValue: "141 / 142 active",
        icon: "HardHat",
      },
      {
        id: "mc-9",
        label: "Vest IoT Hubs",
        value: "98.6%",
        dataSourceField: "vest_iot_hub",
        tintColor: "emerald",
        trendDirection: "up",
        trendValue: "140 / 142 active",
        icon: "Shirt",
      },
      {
        id: "mc-10",
        label: "Boot Grounding Sensors",
        value: "98.1%",
        dataSourceField: "boot_grounding",
        tintColor: "cyan",
        trendDirection: "up",
        trendValue: "139 / 142 active",
        icon: "Footprints",
      },
    ],
    charts: [
      {
        id: "ch-4",
        title: "Connected PPE Compliance by Zone",
        chartType: "bar",
        dataSourceField: "helmet_optical_telemetry",
        description: "Real-time compliance rates from BLE mesh nodes",
      },
      {
        id: "ch-5",
        title: "Safety Vest Hub & Boot Grounding Sensor Health",
        chartType: "donut",
        dataSourceField: "vest_hub_battery_status",
        description: "Active battery status and electrostatic grounding verification",
      },
    ],
    keyInsights: [
      {
        id: "ki-6",
        text: "Single temporary helmet unlatch detected in Zone 2 crane swing perimeter; instant haptic buzz triggered compliance recovery in under 4 seconds.",
      },
      {
        id: "ki-7",
        text: "Electrostatic grounding verified zero charge accumulation during concrete batching transfer.",
      },
    ],
  },
  {
    id: "sec-core-4",
    name: "Time & Operational Impact",
    eyebrow: "OPERATIONAL EFFICIENCY",
    description: "Shift muster clearance latency, weather stand-down tracking, and emergency reaction windows.",
    type: "core",
    icon: "Clock",
    updatedAt: "2026-09-20 11:20",
    metricCards: [
      {
        id: "mc-11",
        label: "Muster Gate Clearance",
        value: "1.8 mins",
        dataSourceField: "gate_clearance",
        tintColor: "emerald",
        trendDirection: "down",
        trendValue: "-45s improvement",
        icon: "Zap",
      },
      {
        id: "mc-12",
        label: "Weather Stand-downs",
        value: "0 hrs",
        dataSourceField: "weather_standdowns",
        tintColor: "green",
        trendDirection: "no-change",
        trendValue: "Optimal wind window",
        icon: "CloudRain",
      },
      {
        id: "mc-13",
        label: "Incident Reaction Window",
        value: "18 secs",
        dataSourceField: "reaction_window",
        tintColor: "purple",
        trendDirection: "down",
        trendValue: "-6s faster response",
        icon: "Timer",
      },
    ],
    charts: [
      {
        id: "ch-6",
        title: "Shift Induction & Clearance Duration",
        chartType: "bar",
        dataSourceField: "attendance_daily_shifts",
        description: "Average muster induction time across rotating crews",
      },
    ],
    keyInsights: [
      {
        id: "ki-8",
        text: "Automated NFC badge scanning reduced shift muster bottleneck by 45 seconds per worker.",
      },
      {
        id: "ki-9",
        text: "Weather safety sensor mesh triggered zero unnecessary tower crane stand-downs.",
      },
    ],
  },
  {
    id: "sec-core-5",
    name: "Key Operational Indicators",
    eyebrow: "SITE TELEMETRY",
    description: "Environmental sensor streaming: ambient acoustics, toxic gas PPM levels, high-altitude wind speed, and thermal comfort.",
    type: "core",
    icon: "Gauge",
    updatedAt: "2026-09-21 09:15",
    metricCards: [
      {
        id: "mc-14",
        label: "Ambient Noise Level",
        value: "68.4 dB",
        dataSourceField: "ambient_noise",
        tintColor: "slate",
        trendDirection: "no-change",
        trendValue: "Below 85 dB threshold",
        icon: "Volume2",
      },
      {
        id: "mc-15",
        label: "Toxic Gas PPM",
        value: "0.02 ppm",
        dataSourceField: "toxic_gas",
        tintColor: "emerald",
        trendDirection: "no-change",
        trendValue: "Safe atmospheric grade",
        icon: "Wind",
      },
      {
        id: "mc-16",
        label: "Average Wind Speed",
        value: "14.2 kts",
        dataSourceField: "wind_speed",
        tintColor: "blue",
        trendDirection: "up",
        trendValue: "Crane limit: 28 kts",
        icon: "Compass",
      },
    ],
    charts: [
      {
        id: "ch-7",
        title: "Continuous Gas PPM & Noise Level Telemetry",
        chartType: "line",
        dataSourceField: "gas_sensor_ppm_levels",
        description: "Continuous IoT sensor stream tracking atmospheric toxic gases and decibels",
      },
    ],
    keyInsights: [
      {
        id: "ki-10",
        text: "All hazardous environmental sensor thresholds remained strictly within OSHA and ISO 45001 limits.",
      },
      {
        id: "ki-11",
        text: "Continuous air quality monitoring verified adequate subterranean airflow during tunnel works.",
      },
    ],
  },
  {
    id: "sec-core-6",
    name: "Supervisory Insights",
    eyebrow: "FIELD SUPERVISION",
    description: "Per-supervisor efficiency, crew hazard response latency, and proactive safety intervention logs.",
    type: "core",
    icon: "Users",
    updatedAt: "2026-09-21 11:15",
    metricCards: [
      {
        id: "mc-17",
        label: "Supervisors on Duty",
        value: "3 leads",
        dataSourceField: "supervisors_count",
        tintColor: "purple",
        trendDirection: "no-change",
        trendValue: "100% shift coverage",
        icon: "UserCheck",
      },
      {
        id: "mc-18",
        label: "Avg Intervention Speed",
        value: "24 secs",
        dataSourceField: "avg_response",
        tintColor: "emerald",
        trendDirection: "down",
        trendValue: "32% faster than SLA",
        icon: "Zap",
      },
      {
        id: "mc-19",
        label: "Safety Alerts Handled",
        value: "39 total",
        dataSourceField: "alerts_handled",
        tintColor: "amber",
        trendDirection: "up",
        trendValue: "All successfully cleared",
        icon: "BellRing",
      },
    ],
    charts: [
      {
        id: "ch-8",
        title: "Supervisor Efficiency & Hazard Response Matrix",
        chartType: "table",
        dataSourceField: "supervisory_response_time",
        description: "Tabular audit matrix of incident response times and resolution speed",
      },
    ],
    keyInsights: [
      {
        id: "ki-12",
        text: "Zone 1 supervisor Sunil M. achieved 18s average intervention latency across 12 automated alerts.",
      },
      {
        id: "ki-13",
        text: "Proactive supervisory engagements prevented 14 potential perimeter incursions during crane lifting.",
      },
    ],
  },
  {
    id: "sec-core-7",
    name: "Device/Unit Operating Hours",
    eyebrow: "EQUIPMENT UTILISATION",
    description: "Active runtime hours vs permissible thermal and duty cycle limits for heavy machinery and IoT nodes.",
    type: "core",
    icon: "Cpu",
    updatedAt: "2026-09-20 18:00",
    metricCards: [
      {
        id: "mc-20",
        label: "Active Runtime Hours",
        value: "320 hrs",
        dataSourceField: "active_operating_hours",
        tintColor: "blue",
        trendDirection: "up",
        trendValue: "360 hrs permissible",
        icon: "Clock",
      },
      {
        id: "mc-21",
        label: "Fleet Health Index",
        value: "98.4%",
        dataSourceField: "fleet_health_index",
        tintColor: "emerald",
        trendDirection: "up",
        trendValue: "All BLE Gateways Operational",
        icon: "Activity",
      },
      {
        id: "mc-22",
        label: "Maintenance Flagged",
        value: "0 units",
        dataSourceField: "flagged_units",
        tintColor: "slate",
        trendDirection: "no-change",
        trendValue: "Next check scheduled Sunday",
        icon: "Wrench",
      },
    ],
    charts: [
      {
        id: "ch-9",
        title: "IoT Node & Sensor Permissible Operating Hours",
        chartType: "bar",
        dataSourceField: "device_daily_operating_hours",
        description: "Logged active operating hours vs permissible safety operating thresholds",
      },
    ],
    keyInsights: [
      {
        id: "ki-14",
        text: "Batching plant mixer unit operated at 88.9% permissible threshold with zero overheating events.",
      },
      {
        id: "ki-15",
        text: "Telemetry battery gateways maintained uninterrupted redundant power supply.",
      },
    ],
  },
  {
    id: "sec-core-8",
    name: "Operational Remarks",
    eyebrow: "ENVIRONMENT & OBSERVATIONS",
    description: "Qualitative shift observations, structural concrete curing remarks, and perimeter geotechnical conditions.",
    type: "core",
    icon: "FileText",
    updatedAt: "2026-09-22 17:00",
    metricCards: [
      {
        id: "mc-23",
        label: "Weather Classification",
        value: "Clear / Dry",
        dataSourceField: "weather",
        tintColor: "cyan",
        trendDirection: "no-change",
        trendValue: "31°C Ambient",
        icon: "Sun",
      },
      {
        id: "mc-24",
        label: "Ground Geotech Status",
        value: "Stable",
        dataSourceField: "geotech_status",
        tintColor: "emerald",
        trendDirection: "no-change",
        trendValue: "Settlement < 1.2mm",
        icon: "Mountain",
      },
    ],
    charts: [],
    keyInsights: [
      {
        id: "ki-16",
        text: "Monsoon winds remained below 28 knots throughout the reporting window. High-altitude crane operations in Zone 2 completed without perimeter breaches.",
      },
      {
        id: "ki-17",
        text: "Grounding sensors verified zero electrostatic hazard during heavy concrete pumping.",
      },
    ],
  },
  {
    id: "sec-core-9",
    name: "Improvement & Action Plan",
    eyebrow: "CORRECTIVE ACTIONS",
    description: "Continuous safety improvement items, corrective action tracking, responsible lead assignment, and resolution timelines.",
    type: "core",
    icon: "CheckSquare",
    updatedAt: "2026-09-22 12:45",
    metricCards: [
      {
        id: "mc-25",
        label: "Open Action Items",
        value: "3 pending",
        dataSourceField: "open_actions",
        tintColor: "amber",
        trendDirection: "down",
        trendValue: "2 resolved this week",
        icon: "AlertCircle",
      },
      {
        id: "mc-26",
        label: "SLA Resolution Rate",
        value: "91.4%",
        dataSourceField: "sla_rate",
        tintColor: "emerald",
        trendDirection: "up",
        trendValue: "+4.1% MoM",
        icon: "TrendingUp",
      },
      {
        id: "mc-27",
        label: "Upcoming Deadlines",
        value: "2 items",
        dataSourceField: "upcoming_deadlines",
        tintColor: "purple",
        trendDirection: "no-change",
        trendValue: "Due within 7 days",
        icon: "Calendar",
      },
    ],
    charts: [
      {
        id: "ch-10",
        title: "Mitigation Action Plan Progress & Resolution Timeline",
        chartType: "table",
        dataSourceField: "action_plan_completion_rate",
        description: "High-priority remedial actions and owner accountability matrix",
      },
    ],
    keyInsights: [
      {
        id: "ki-18",
        text: "Deploy secondary BLE repeater to eliminate 40-second response latency for Subcontractor EHS in Zone 3.",
      },
      {
        id: "ki-19",
        text: "Recalibrate anti-slip electrostatic grounding threshold on muddy access ramps.",
      },
      {
        id: "ki-20",
        text: "Compile verified SHA-256 cryptographic hashes for third-party regulatory signoff.",
      },
    ],
  },
];

export function getInitialLibrarySections(): LibrarySection[] {
  // Zero-Fallback Policy: Database is the single source of truth.
  // Purge any stale legacy localStorage entries
  if (typeof window !== "undefined") {
    try {
      localStorage.removeItem("ayantrai_library_sections");
    } catch (_) {}
  }
  return [];
}


