"use client";

import { TemplateBlock, ReportTemplate } from "../types/reportModuleTypes";

export const defaultBlocks: TemplateBlock[] = [
  {
    id: "blk-1",
    type: "key_metrics",
    title: "Key Metrics",
    description: "KPI row (attendance rate, compliance rate, risk-free hours, devices deployed)",
    enabled: true,
    order: 1,
    graphs: [
      {
        id: "grp-km-1",
        title: "Workforce Safety KPI Executive Summary",
        type: "bar",
        dataSource: "ppe_sensor_compliance",
        description: "Comparative gauge across active contractors and workforce crews",
      },
    ],
  },
  {
    id: "blk-2",
    type: "attendance_trends",
    title: "Attendance Trends",
    description: "Line chart + insight text (department-wise and vendor-wise breakdown)",
    enabled: true,
    order: 2,
    graphs: [
      {
        id: "grp-att-1",
        title: "Daily Shift Muster Adherence",
        type: "line",
        dataSource: "attendance_daily_shifts",
        description: "Shift 1 vs Shift 2 daily check-in volume",
      },
      {
        id: "grp-att-2",
        title: "Subcontractor Headcount Distribution",
        type: "pie",
        dataSource: "attendance_vendor_distribution",
        description: "Muster distribution across primary civil and MEP vendors",
      },
    ],
  },
  {
    id: "blk-3",
    type: "ppe_compliance_trends",
    title: "PPE Compliance Trends",
    description: "Bar chart + insight text (Smart Helmet, Vest IoT Hub, Safety Boot grounding)",
    enabled: true,
    order: 3,
    graphs: [
      {
        id: "grp-ppe-1",
        title: "Connected PPE Compliance by Zone",
        type: "bar",
        dataSource: "helmet_optical_telemetry",
        description: "Real-time compliance rates from BLE mesh nodes",
      },
      {
        id: "grp-ppe-2",
        title: "Safety Vest Hub & Boot Grounding Sensor Health",
        type: "donut",
        dataSource: "vest_hub_battery_status",
        description: "Active battery status and electrostatic grounding verification",
      },
    ],
  },
  {
    id: "blk-4",
    type: "supervisory_insights",
    title: "Supervisory Insights",
    description: "Table (per-supervisor efficiency, response time, alert handling)",
    enabled: true,
    order: 4,
    graphs: [
      {
        id: "grp-sup-1",
        title: "Supervisor Efficiency & Hazard Response Matrix",
        type: "table",
        dataSource: "supervisory_response_time",
        description: "Tabular audit matrix of incident response times and resolution speed",
      },
    ],
  },
  {
    id: "blk-5",
    type: "device_utilisation",
    title: "Device Utilisation",
    description: "Progress bar (operating hours vs. permissible hours)",
    enabled: true,
    order: 5,
    graphs: [
      {
        id: "grp-dev-1",
        title: "IoT Node & Sensor Permissible Operating Hours",
        type: "bar",
        dataSource: "device_daily_operating_hours",
        description: "Logged active operating hours vs permissible safety operating thresholds",
      },
    ],
  },
  {
    id: "blk-6",
    type: "operational_remarks",
    title: "Operational Remarks",
    description: "Text summary with environmental and shift-level observations",
    enabled: true,
    order: 6,
    graphs: [],
  },
  {
    id: "blk-7",
    type: "improvement_action_plan",
    title: "Improvement & Action Plan",
    description: "Action matrix table (area, focus, owner, target date, status)",
    enabled: true,
    order: 7,
    graphs: [
      {
        id: "grp-act-1",
        title: "Mitigation Action Plan Progress & Resolution Timeline",
        type: "table",
        dataSource: "action_plan_completion_rate",
        description: "High-priority remedial actions and owner accountability matrix",
      },
    ],
  },
];

export const initialTemplates: ReportTemplate[] = [
  {
    id: "TPL-001",
    name: "Sitesafe Monthly Workforce-Safety & ISO 45001 Report",
    description: "Flagship monthly workforce safety report with full 7-section telemetry and supervisory audit trail.",
    site_id: "SITE-01",
    site_name: "Nx-One Tower Pilot Site (Greater Noida)",
    blocks: defaultBlocks,
    status: "active",
    created_by: "Vikram Seth (Site Admin)",
    created_at: "2026-09-18 10:30 AM",
    approved_by: "Dr. Vikram Seth (Superadmin)",
    approved_at: "2026-09-19 02:15 PM",
    version: "v1.2",
  },
  {
    id: "TPL-002",
    name: "Tunnel Excavation & Subterranean Airflow Audit",
    description: "High-frequency geotechnical and toxic gas compliance protocol template for underground tunnels.",
    site_id: "SITE-02",
    site_name: "Metro Line 4 Underground Tunnel (Mumbai)",
    blocks: defaultBlocks.filter((b) => b.type !== "device_utilisation"),
    status: "rejected",
    rejection_reason: "Missing toxic gas sensor calibration block and emergency protocol sign-off checklist.",
    approved_by: "Dr. Vikram Seth (Superadmin)",
    approved_at: "2026-09-22 11:30 AM",
    created_by: "Anita Sharma (Tunnel Safety Lead)",
    created_at: "2026-09-22 09:10 AM",
    version: "v1.0",
  },
  {
    id: "TPL-003",
    name: "High-Speed Rail Viaduct Pre-Cast Concrete Compliance",
    description: "Structural erection safety and crane radius geofencing daily telemetry template.",
    site_id: "SITE-03",
    site_name: "High-Speed Rail Viaduct C-2 (Ahmedabad)",
    blocks: defaultBlocks,
    status: "pending",
    created_by: "Rajesh Gupta (Civil Ops Admin)",
    created_at: "2026-09-21 04:45 PM",
    version: "v0.9",
  },
];
